// PresentationSpawnSystem.cs
// Spawns and syncs visual GameObjects for ECS entities
// Location: Assets/GameData/TechTree/Presentation/Spawn/PresentationSpawnSystem.cs
// Per-entity builders live as partials in their entity folders (Smelter,
// Vault of Almierra, Border LargeNode, Alanthor Wall set, and the three
// Resources nodes); dead procedural Hall/Hut/Barracks builders deleted 2026-08-12.

using System.Collections.Generic;
using UnityEngine;
using Unity.Entities;
using Unity.Transforms;
using TheWaningBorder.Presentation;
using TheWaningBorder.World.Terrain;
using TheWaningBorder.Bootstrap;
using TheWaningBorder.Entities;

using TheWaningBorder.Core;
// Fix #204: marked partial. The obstacle and wall procedural generators
// have been extracted to PresentationSpawnSystem.Obstacles.cs and
// PresentationSpawnSystem.Walls.cs to reduce this file's line count.
public partial class PresentationSpawnSystem : MonoBehaviour
{
    public static PresentationSpawnSystem Instance { get; private set; }

    // Prefab mapping: PresentationId -> Prefab path in Resources
    // IDs must match the PresentationID constants in each entity factory class
    private static readonly Dictionary<int, string> PrefabPaths = new()
    {
        // Buildings - Era 1 Core (procedural — Hall/Hut/Barracks generated by
        // ProceduralBuildingGenerator. The hand-authored *_base prefabs are
        // shelved for now; restore via PrefabPaths + remove the procedural
        // switch cases when ready.)
        { 100, "Procedural/Hall" },                        // Hall.PresentationID = 100
        { 101, "Prefabs/Buildings/GatherersHut" },       // GatherersHut.PresentationID = 101
        { 102, "Procedural/Hut" },                          // Hut.PresentationID = 102
        { 510, "Procedural/Barracks" },                    // Barracks.PresentationID = 510

        // Buildings - Era 1 Advanced
        { 520, "Prefabs/Buildings/ShrineOfAhridan" },    // ShrineOfAhridan.PresentationID = 520 — bearded-man-with-crystal statue (WireTempleAndChapelVisuals)
        { 521, "Prefabs/Buildings/TempleOfRidan" },      // TempleOfRidan.PresentationID = 521
        { 530, "Procedural/Vault" },                     // VaultOfAlmierra.PresentationID = 530 — intercepted by the authored-visuals switch (CreateProceduralVault); never loaded
        { 540, "Prefabs/Buildings/FiendstoneKeep" },     // FiendstoneKeep.PresentationID = 540 — intercepted by the authored-visuals switch (FiendstoneKeepVisual); never loaded

        // Units
        { 200, "Prefabs/Units/SK_Character_Human_Peasant" }, // Worker (PresentationID 200) — single-character Humanoid peasant (auto-avatar, no duplicate bones)
        { 201, "Prefabs/Units/Swordsman" },              // Swordsman.PresentationID = 201
        { 202, "Prefabs/Units/Archer" },                 // Archer.PresentationID = 202
        { 203, "Prefabs/Units/Miner" },                  // Miner.PresentationID = 203
        { 206, "Prefabs/Units/Scout" },                  // Scout.PresentationID = 206
        { 207, "Prefabs/Units/Litharch" },               // Litharch.PresentationID = 207
        { 250, "Prefabs/Units/Ledger" },                 // Ledger.PresentationID = 250 — floating automaton (built by WireLedgerVisuals)
        { 387, "Prefabs/Units/Litharch" },               // Lorekeeper (Antiquity) — reuses the robed Litharch visual
        // Feraldis fire-and-blood roster (design 2026-08-05). Placeholder
        // art: the Bloodletter and Suicidal reuse the Swordsman visual until
        // Feraldis models land. (Feraldis_Spearman shares the Spearman's
        // pid 330 outright, so it needs no entry.)
        { 342, "Prefabs/Units/Swordsman" },              // Bloodletter.PresentationID = 342
        { 343, "Prefabs/Units/Swordsman" },              // Suicidal.PresentationID = 343
        { 344, "Prefabs/Units/Archer" },                 // Firethrower.PresentationID = 344 (placeholder art)
        { 345, "Prefabs/Units/Scout" },                  // Eagle.PresentationID = 345 (placeholder art)
        // New sect units live at 405-407 — 388-403 are all taken (chapels
        // 390-399 plus the 400-403 Forest/Rock/deposit block; chapel
        // overflow sits at 412/413). A
        // duplicate key throws in the static initializer and kills ALL
        // presentation (invisible units). If you add IDs here, run a
        // duplicate-key scan over this file first.
        { 405, "Prefabs/Units/SK_Character_Human_Peasant" }, // Tinker (Renewal) — reuses the Worker visual
        { 406, "Prefabs/Units/Litharch" },               // Inquisitor (Justice) — reuses the robed Litharch visual
        { 407, "Prefabs/Units/Swordsman" },              // Warbreaker (War) — reuses the Swordsman visual

        // Creatures & Resources
        { 300, "Prefabs/Creatures/Creature" },            // Creature.PresentationID = 300
        { 301, "Prefabs/Resources/BorderNode" },         // VeilstoneOutcropping/BorderNode.PresentationID = 301

        // Nature Obstacles (procedurally generated)
        { 400, "Procedural/Forest" },                      // ForestCluster (generated at runtime)
        { 401, "Procedural/Rock" },                        // RockFormation (generated at runtime)

        // Resources (procedurally generated)
        { 402, "Procedural/IronDeposit" },                 // IronDeposit (generated at runtime)
        { 403, "Procedural/VeilsteelDeposit" },            // Veilsteel "Sharp Crystals" node (generated at runtime)

        // Alanthor Walls (procedurally generated)
        { 550, "Procedural/WallHub" },                      // Alanthor Wall Hub (generated at runtime)
        { 551, "Procedural/WallSegment" },                   // Alanthor Wall Segment (legacy, no longer spawned)
        { 552, "Procedural/WallInstance" },                  // Alanthor Wall Instance (small wall piece)
        { 553, "Procedural/WallTower" },                     // Alanthor Wall Tower (upgraded instance)
        { 554, "Procedural/WallGate" },                      // Alanthor Wall Gate (upgraded instance)

        // Alanthor Buildings (procedurally generated)
        { 560, "Procedural/Smelter" },                       // Alanthor Smelter/Forge (generated at runtime)

        // The Border (procedurally generated)
        { 311, "Procedural/BorderGround" },                  // Border Ground tile (generated at runtime)

        // Veilstone Nodes (procedurally generated)
        { 310, "Procedural/BorderMainNode" },                // BorderMainNode (generated at runtime)

        // Veilstone Units (prefabs in Resources/Prefabs/Border/Units/)
        { 320, "Prefabs/Border/Units/Crystallings" },            // Crystalling unit prefab
        { 321, "Prefabs/Border/Units/Veilstingers" },            // Veilstinger unit prefab
        { 322, "Prefabs/Border/Units/Godsplinters" },            // Godsplinter unit prefab

        // Runai culture buildings (procedurally generated)
        { 350, "Procedural/RunaiOutpost" },                       // Runai_Outpost
        { 351, "Procedural/RunaiTradeHub" },                      // Runai_TradeHub
        { 352, "Procedural/RunaiBazaar" },                        // ThessarasBazaar
        { 353, "Procedural/RunaiSiegeWorkshop" },                 // Runai_SiegeWorkshop
        { 355, "Procedural/RunaiTradingPost_or_AlanthorPracticeRange" }, // Shared ID

        // Alanthor culture buildings (procedurally generated)
        { 354, "Procedural/AlanthorTower" },                      // Alanthor_Tower
        { 356, "Procedural/AlanthorRoyalStable" },                // Alanthor_RoyalStable
        { 357, "Procedural/AlanthorSiegeYard" },                  // Alanthor_SiegeYard

        // Feraldis culture buildings (procedurally generated)
        { 358, "Procedural/FeraldisHuntingLodge" },               // Feraldis_HuntingLodge
        { 359, "Procedural/FeraldisLoggingStation" },             // Feraldis_LoggingStation
        { 360, "Procedural/FeraldisLonghouse" },                  // Feraldis_Longhouse
        { 361, "Procedural/FeraldisTotemTower" },                 // Feraldis_Tower
        { 362, "Procedural/FeraldisSiegeYard" },                  // Feraldis_SiegeYard
        { 363, "Procedural/FeraldisLonghouse" },                  // Feraldis_Pasture (reuses the longhouse shell)
        { 364, "Procedural/AlanthorSiegeYard" },                  // Mine (placeholder shell)

        // Chapels — pid 390 + sect index (see BuildingFactory.ChapelPidForSect;
        // Ruin/Wrath sit at 412/413: 400-403 are Forest/Rock/deposits and
        // 410 is the BazaarWagon). Six authored roof
        // styles, two per affinity culture; the unauthored sects reuse their
        // cluster-mate's prefab until they get their own (2026-08-02).
        { 390, "Prefabs/Buildings/Chapels/Chapel_Antiquity" },   // Antiquity (Alanthor — ziggurat roof)
        { 391, "Prefabs/Buildings/Chapels/Chapel_Renewal" },     // Renewal (Alanthor — gabled slate roof)
        { 392, "Prefabs/Buildings/Chapels/Chapel_Antiquity" },   // Fortitude (reuses Alanthor style)
        { 393, "Prefabs/Buildings/Chapels/Chapel_Renewal" },     // Reclamation (reuses Alanthor style)
        { 394, "Prefabs/Buildings/Chapels/Chapel_Silence" },     // Silence (Runai — tent spire roof)
        { 395, "Prefabs/Buildings/Chapels/Chapel_Justice" },     // Justice (Runai — golden dome)
        { 396, "Prefabs/Buildings/Chapels/Chapel_Silence" },     // Veneration (reuses Runai style)
        { 397, "Prefabs/Buildings/Chapels/Chapel_Justice" },     // Witness (reuses Runai style)
        { 398, "Prefabs/Buildings/Chapels/Chapel_War" },         // War (Feraldis — horned roof)
        { 399, "Prefabs/Buildings/Chapels/Chapel_Ash" },         // Ash (Feraldis — smokestack roof)
        { 412, "Prefabs/Buildings/Chapels/Chapel_War" },         // Ruin (reuses Feraldis style)
        { 413, "Prefabs/Buildings/Chapels/Chapel_Ash" },         // Wrath (reuses Feraldis style)
    };

    // Culture-specific prefab overrides. Looked up before PrefabPaths so an aged-up
    // Alanthor/Runai/Feraldis player gets a culture-themed model where one exists,
    // while pre-culture (Cultures.None) factions still get the default prefab.
    // Currently empty while we run on procedural Hall/Hut/Barracks; the Alanthor
    // hand-authored variant is shelved alongside the others. Add entries here
    // when the prefabs come back in.
    private static readonly Dictionary<(int presentationId, byte culture), string> CulturePrefabOverrides = new()
    {
    };

    /// <summary>Presentation ID for border ground tiles.</summary>
    private const int BorderGroundPresentationId = 311;

    // Longbowman (see Entities/Units/Longbowman.cs). Its corpses linger and
    // dissolve via CorpseDissolver instead of vanishing on death.
    private const int LongbowmanPresentationId = 205;

    // Phase-lock "draw lead": seconds before the reload completes that the
    // draw→shoot is cued, so the bow's release lands on the arrow spawn. ≈ draw
    // (61f) + the recoil up to the loose (~most of 41f) @ 60 fps. Tunable — see
    // UnitAnimationSync.AttackCycleSeconds.
    private const float LongbowmanAttackCycleSeconds = 1.45f;

    // Building model orientation offset. Authoring convention: building
    // prefabs + procedural meshes face -Z, but the default RTS camera
    // looks at +Z, so visuals need a 180° Y-rotation to face the camera.
    // ECS LocalTransform.Rotation stays clean (mouse-wheel yaw); the
    // offset is applied only when writing the GameObject rotation.
    private static readonly Quaternion BuildingVisualOffsetY180 = Quaternion.Euler(0f, 180f, 0f);

    /// <summary>
    /// <summary>
    /// Asset-pack character prefabs — and our unit prefab VARIANTS of them
    /// (Litharch/Scholar/Sentinel/Berserker/... are variants of ExplosiveLLC
    /// Warrior characters) — inherit the pack's demo player-controller stack:
    /// WarriorAnimsFREE input/movement scripts that poll unbound input axes
    /// ("Input Button Attack is not setup" spam) and SuperCharacterController
    /// physics that writes invalid layers and fights the ECS movement sync.
    /// Strip every such behaviour from instantiated visuals; renderers,
    /// colliders (needed for selection), and the Animator survive.
    ///
    /// Dependents are destroyed before their RequireComponent dependencies:
    /// pass 1 removes the pack's namespaced scripts, pass 2 the controller
    /// core they depend on.
    /// </summary>
    private static void StripThirdPartyControllers(GameObject go)
    {
        var behaviours = go.GetComponentsInChildren<MonoBehaviour>(true);

        // Pass 1: namespaced pack scripts (WarriorInputController,
        // WarriorMovementController, WarriorController, IKHands, ...).
        for (int i = 0; i < behaviours.Length; i++)
        {
            var b = behaviours[i];
            if (b == null) continue; // missing-script slot
            string ns = b.GetType().Namespace ?? string.Empty;
            if (ns.StartsWith("WarriorAnimsFREE") || ns.StartsWith("RPGCharacterAnims"))
            {
                DestroyImmediate(b);
                behaviours[i] = null;
            }
        }

        // Pass 2: the controller core (global namespace) the pack scripts
        // RequireComponent — safe to remove now that dependents are gone.
        for (int i = 0; i < behaviours.Length; i++)
        {
            var b = behaviours[i];
            if (b == null) continue;
            string typeName = b.GetType().Name;
            if (typeName == "SuperCharacterController" || typeName == "SuperStateMachine")
            {
                DestroyImmediate(b);
            }
        }

        // Asset-pack clips carry baked AnimationEvents (FootL/FootR footsteps,
        // Hit, ...) whose receiver scripts are exactly what we stripped above —
        // without a receiver every loop logs "AnimationEvent ... has no
        // receiver". Game logic is ECS-driven, so presentation animators don't
        // consume events at all: stop firing them.
        var animators = go.GetComponentsInChildren<Animator>(true);
        for (int i = 0; i < animators.Length; i++)
            animators[i].fireEvents = false;
    }

    /// <summary>
    /// Apply the +180° Y visual offset for any entity with BuildingTag.
    /// Units pass through unchanged.
    /// </summary>
    private Quaternion VisualRotation(Entity entity, Quaternion entityRot)
    {
        if (_em.HasComponent<BuildingTag>(entity))
            return entityRot * BuildingVisualOffsetY180;
        return entityRot;
    }

    // Fallback prefabs if specific one not found
    private GameObject _fallbackUnitPrefab;
    private GameObject _fallbackBuildingPrefab;

    // Track which entities already have visuals
    private HashSet<Entity> _spawnedEntities = new();

    /// <summary>
    /// Per-view sync state. SyncTransforms runs over EVERY presentation entity
    /// every frame, and most of them are buildings, wall modules, obstacles and
    /// resource nodes that never move once placed. For each of those it was
    /// still paying, every frame: a Terrain.SampleHeight, two GetComponent
    /// walks, and three transform writes. A finished AI perimeter alone is
    /// ~165 wall modules per faction, so this scaled straight into the frame
    /// time as the map filled up. Caching the resolved components and the
    /// last-written transform lets a static entity cost one comparison.
    /// </summary>
    private sealed class ViewSync
    {
        /// <summary>The GameObject the cached components were read off. A
        /// building that swaps prefab (level-up, culture variant) gets a NEW
        /// view for the same entity, so compare before trusting the cache.
        /// </summary>
        public GameObject View;
        public ProceduralScaleTag ScaleTag;
        public BuildingRiseData Rise;

        public bool Primed;
        public Unity.Mathematics.float3 LastPos;
        public Unity.Mathematics.quaternion LastRot;
        public float LastScale;
        public bool LastUnderConstruction;
        /// <summary>TerrainUtility.TerrainVersion at the last write — a
        /// changed value means the ground moved under this visual (terrain
        /// finished generating, or the scene swapped) and the cached height
        /// must be re-sampled.</summary>
        public int LastTerrainVersion;

        // ── Fixed-step interpolation ────────────────────────────────────
        //
        // Under lockstep the simulation publishes transforms in discrete jumps
        // (once per tick, not once per frame), and a view snapped straight to
        // them steps visibly between ticks — the whole game reads as though it
        // were running at the tick rate. These carry the segment being played
        // out between the last two simulated transforms.
        //
        // Unused when the simulation free-runs per frame: there is nothing to
        // interpolate then, and doing it anyway would add a frame of lag.

        /// <summary>Where the view was when the current segment started.</summary>
        public Unity.Mathematics.float3 FromPos;
        public Quaternion FromRot;
        /// <summary>The simulated transform the segment is heading for.</summary>
        public Unity.Mathematics.float3 ToPos;
        public Quaternion ToRot;
        /// <summary>0..1 progress through the current segment.</summary>
        public float SegmentT;
        /// <summary>Last transform written to the GameObject.</summary>
        public Unity.Mathematics.float3 RenderPos;
        public Quaternion RenderRot;
    }

    /// <summary>
    /// A simulated jump longer than this is a teleport (spawn, snap-to-passable
    /// escape, rally warp), not movement — interpolating across it would drag
    /// the visual through everything in between.
    /// </summary>
    private const float TeleportSnapDistanceSq = 8f * 8f;

    private readonly Dictionary<Entity, ViewSync> _viewSync = new();

    /// <summary>Reused scratch for the per-frame destroyed-entity sweep.</summary>
    private readonly List<Entity> _staleScratch = new();

    // Cache
    private Unity.Entities.World _world;
    private EntityManager _em;
    private EntityQuery _presentationQuery;

    // Throttle SyncTransforms to ~15fps to reduce per-frame cost
    private float _syncTimer;

    void Awake()
    {
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
            return;
        }
        Instance = this;

        // Create fallback primitives
        _fallbackUnitPrefab = CreateFallbackPrefab("FallbackUnit", PrimitiveType.Capsule, 0.5f);
        _fallbackBuildingPrefab = CreateFallbackPrefab("FallbackBuilding", PrimitiveType.Cube, 2f);
    }

    void Start()
    {
        _world = Unity.Entities.World.DefaultGameObjectInjectionWorld;
        if (_world != null && _world.IsCreated)
        {
            _em = _world.EntityManager;
            _presentationQuery = _em.CreateEntityQuery(
                ComponentType.ReadOnly<PresentationId>(),
                ComponentType.ReadOnly<LocalTransform>()
            );
        }
    }

    void Update()
    {
        if (_world == null || !_world.IsCreated) return;

        // Instrumented (2026-08-16 perf sweep): three unthrottled full sweeps
        // per frame — the prime suspect for the unattributed FRAME spikes.
        double t0 = UnityEngine.Time.realtimeSinceStartupAsDouble;
        CleanupDestroyedEntities();
        SpawnMissingVisuals();
        SyncTransforms();
        TheWaningBorder.Core.Diagnostics.PerfSpikeLog.Report("PresentSync",
            (UnityEngine.Time.realtimeSinceStartupAsDouble - t0) * 1000.0);
    }

    /// <summary>
    /// Detects ECS entities that have been destroyed (e.g., by DeathSystem)
    /// and cleans up their corresponding GameObjects.
    /// </summary>
    private void CleanupDestroyedEntities()
    {
        if (EntityViewManager.Instance == null) return;

        // Collect stale entities (can't modify HashSet during iteration).
        // Reused across frames — this ran every frame and allocated a fresh
        // List even on the overwhelmingly common frame where nothing died.
        _staleScratch.Clear();

        foreach (var entity in _spawnedEntities)
        {
            if (!_em.Exists(entity))
            {
                _staleScratch.Add(entity);
            }
        }

        foreach (var entity in _staleScratch)
        {
            _spawnedEntities.Remove(entity);
            _viewSync.Remove(entity);

            if (EntityViewManager.Instance.TryGetView(entity, out var go))
            {
                EntityViewManager.Instance.UnregisterView(entity);
                if (go != null)
                {
                    var outcroppingAnim = go.GetComponent<TheWaningBorder.Presentation.VeilstoneOutcroppingCrystalAnimator>();
                    var corpse = go.GetComponent<CorpseDissolver>();
                    if (outcroppingAnim != null)
                    {
                        // Hand off to the Shatter Stone animator: it spawns
                        // the asset's debris pieces (which outlive this GO,
                        // they aren't parented) and owns the final Destroy.
                        outcroppingAnim.BeginDeath();
                    }
                    else if (corpse != null)
                    {
                        // Longbowman corpse: let it finish the death animation,
                        // linger in the final pose, then dissolve. It owns the
                        // final Destroy of this GameObject.
                        corpse.BeginDeath();
                    }
                    else
                    {
                        Destroy(go);
                    }
                }
            }
        }
    }

    private void SpawnMissingVisuals()
    {
        if (_presentationQuery == null) return;

        var entities = _presentationQuery.ToEntityArray(Unity.Collections.Allocator.Temp);
        var presentations = _presentationQuery.ToComponentDataArray<PresentationId>(Unity.Collections.Allocator.Temp);
        var transforms = _presentationQuery.ToComponentDataArray<LocalTransform>(Unity.Collections.Allocator.Temp);

        for (int i = 0; i < entities.Length; i++)
        {
            var entity = entities[i];

            // Skip if already spawned
            if (_spawnedEntities.Contains(entity)) continue;

            // Skip if EntityViewManager already has it
            if (EntityViewManager.Instance != null &&
                EntityViewManager.Instance.TryGetView(entity, out _))
            {
                _spawnedEntities.Add(entity);
                continue;
            }

            var presentationId = presentations[i].Id;
            var transform = transforms[i];

            // Spawn the visual
            var go = SpawnVisual(entity, presentationId, transform);
            if (go != null)
            {
                // Register with EntityViewManager
                if (EntityViewManager.Instance != null)
                    EntityViewManager.Instance.RegisterView(entity, go);

                _spawnedEntities.Add(entity);

            }
        }

        entities.Dispose();
        presentations.Dispose();
        transforms.Dispose();
    }

    private GameObject SpawnVisual(Entity entity, int presentationId, LocalTransform transform)
    {
        // Get position and adjust Y to terrain height using shared utility
        Vector3 pos = transform.Position;
        pos.y = TerrainUtility.GetHeight(pos.x, pos.z);

        // === PROCEDURAL OBSTACLES: generate compound GameObjects instead of loading prefabs ===
        if (presentationId == ObstacleBootstrap.ForestPresentationId)
        {
            float radius = _em.HasComponent<Radius>(entity) ? _em.GetComponentData<Radius>(entity).Value : 5f;
            var go = CreateProceduralForest(pos, radius, entity);
            return go;
        }
        if (presentationId == ObstacleBootstrap.RockPresentationId)
        {
            float radius = _em.HasComponent<Radius>(entity) ? _em.GetComponentData<Radius>(entity).Value : 3f;
            var go = CreateProceduralRockFormation(pos, radius, entity);
            return go;
        }
        if (presentationId == IronDepositBootstrap.IronDepositPresentationId)
        {
            var go = CreateProceduralIronDeposit(pos, entity);
            return go;
        }
        if (presentationId == TheWaningBorder.Bootstrap.VeilsteelDepositBootstrap.VeilsteelDepositPresentationId)
        {
            var go = CreateProceduralVeilsteelDeposit(pos, entity);
            return go;
        }

        // === ALANTHOR WALLS: procedural hub, instances, towers, gates ===
        if (presentationId == TheWaningBorder.Entities.AlanthorWall.HubPresentationID)
        {
            var go = CreateProceduralWallHub(pos, entity);
            return go;
        }
        if (presentationId == 551) // Legacy segment — kept for backward compat
        {
            var go = CreateProceduralWallSegment(pos, entity);
            return go;
        }
        if (presentationId == TheWaningBorder.Entities.AlanthorWall.InstancePresentationID)
        {
            var go = CreateProceduralWallInstance(pos, entity);
            AttachConstructionAnimation(go);
            return go;
        }
        if (presentationId == TheWaningBorder.Entities.AlanthorWall.TowerPresentationID)
        {
            var go = CreateProceduralWallTower(pos, entity);
            AttachConstructionAnimation(go);
            return go;
        }
        if (presentationId == TheWaningBorder.Entities.AlanthorWall.GatePresentationID)
        {
            var go = CreateProceduralWallGate(pos, entity);
            AttachConstructionAnimation(go);
            return go;
        }

        // === ALANTHOR SMELTER: procedural forge building ===
        if (presentationId == TheWaningBorder.Entities.Smelter.PresentationID)
        {
            var go = CreateProceduralSmelter(pos, entity);
            AttachConstructionAnimation(go);
            return go;
        }

        // === Alanthor + Age-0 choice authored visuals (tech-tree implementation) ===
        // High-detail procedural builders co-located with their entities. Units
        // get the hand-rolled tail (collider + EntityReference; their animator
        // MonoBehaviours self-tint the faction accents); buildings route through
        // FinishProceduralBuilding for rotation/collider/rise/damage plus the
        // faction marker for their Stripe_* accent parts. The seed keeps the
        // deterministic-randomness convention (entity.Index + salt).
        {
            GameObject authored = null;
            bool authoredIsBuilding = false;
            bool spawnsFinished = false;   // Field Hospital raises pre-built

            // Real authored art SUPERSEDES the procedural placeholder. These
            // builders were written as stand-ins until a building had a model;
            // because this switch runs before the prefab resolution below, a
            // freshly authored prefab was silently ignored and the placeholder
            // kept rendering (the Royal Stable kept its procedural look after
            // being given real art). Checked generically off the SO prefab's
            // layout, so every future building supersedes its own placeholder
            // the moment its art lands — no per-id edit here.
            bool authoredPrefabWins =
                _em.HasComponent<BuildingTag>(entity)
                && TechCatalog.TryGetPrefab(presentationId, out var supersedingPrefab)
                && supersedingPrefab != null
                && TheWaningBorder.Presentation.BuildingVariantVisual.HasVariantLayout(supersedingPrefab);

            switch (authoredPrefabWins ? -1 : presentationId)
            {
                case 368: authored = TheWaningBorder.Presentation.SpearmanVisual.Build(entity.Index + 368); break;
                // 201: the Swordsman prefab is a Synty variant whose skinned-mesh
                // guid resolves to nothing on disk (invisible). Authored rig wins.
                case 201: authored = TheWaningBorder.Presentation.SwordsmanVisual.Build(entity.Index + 201); break;
                case 202: authored = TheWaningBorder.Presentation.ArcherVisual.Build(entity.Index + 202); break;
                case 349: authored = TheWaningBorder.Presentation.OutriderVisual.Build(entity.Index + 349); break;
                case 336: authored = TheWaningBorder.Presentation.CataphractVisual.Build(entity.Index + 336); break;
                case 251: authored = TheWaningBorder.Presentation.KingLexorVisual.Build(entity.Index + 251); break;
                case 346: authored = TheWaningBorder.Presentation.NoblemanVisual.Build(entity.Index + 346); break;
                case 347: authored = TheWaningBorder.Presentation.BatteringRamVisual.Build(entity.Index + 347); break;
                case 348: authored = TheWaningBorder.Presentation.TrebuchetVisual.Build(entity.Index + 348); break;
                case 356: authored = TheWaningBorder.Presentation.RoyalStableVisual.Build(entity.Index + 356); authoredIsBuilding = true; break;
                case 357: authored = TheWaningBorder.Presentation.SiegeYardVisual.Build(entity.Index + 357); authoredIsBuilding = true; break;
                case 354: authored = TheWaningBorder.Presentation.WatchTowerVisual.Build(entity.Index + 354); authoredIsBuilding = true; break;
                case 358: authored = TheWaningBorder.Presentation.FieldHospitalVisual.Build(entity.Index + 358); authoredIsBuilding = true; spawnsFinished = true; break;
                // Age 0 choice buildings (culture-neutral):
                // 530: the Vault generator predates this switch and already fits
                //      its own collider + EntityReference at its tail; both are
                //      idempotent under FinishProceduralBuilding (the fitter
                //      reuses the root BoxCollider, the reference is get-or-add),
                //      which adds the rotation / sink-rise construction animation /
                //      faction marker the generator lacks. No double-finishing.
                case 530: authored = CreateProceduralVault(pos, entity); authoredIsBuilding = true; break;
                case 540: authored = TheWaningBorder.Presentation.FiendstoneKeepVisual.Build(entity.Index + 540); authoredIsBuilding = true; break;
                // Sect buildings (561-564) — one per sect, capped at 5 per
                // faction. Alanthor cluster; the other eight land with their
                // pass. docs/Design/Sects.md section 1.
                // Sect units. These pids already had PrefabPaths rows pointing
                // at borrowed Synty/Litharch stand-ins; this switch runs first,
                // so the authored rigs win without touching that dictionary.
                case 370: authored = TheWaningBorder.Presentation.ScarGuardVisual.Build(entity.Index + 370); break;
                case 371: authored = TheWaningBorder.Presentation.GolemAutarkVisual.Build(entity.Index + 371); break;
                case 372: authored = TheWaningBorder.Presentation.StoneWardenVisual.Build(entity.Index + 372); break;
                case 387: authored = TheWaningBorder.Presentation.LorekeeperVisual.Build(entity.Index + 387); break;

                case 561: authored = TheWaningBorder.Presentation.ReliquaryVisual.Build(entity.Index + 561); authoredIsBuilding = true; break;
                case 562: authored = TheWaningBorder.Presentation.MendingHallVisual.Build(entity.Index + 562); authoredIsBuilding = true; break;
                case 563: authored = TheWaningBorder.Presentation.StoneholdVisual.Build(entity.Index + 563); authoredIsBuilding = true; break;
                case 564: authored = TheWaningBorder.Presentation.VeilworksVisual.Build(entity.Index + 564); authoredIsBuilding = true; break;
                case 565: authored = TheWaningBorder.Presentation.MusterYardVisual.Build(entity.Index + 565); authoredIsBuilding = true; break;
            }

            if (authored != null)
            {
                authored.transform.position = pos;

                if (authoredIsBuilding)
                {
                    var finished = FinishProceduralBuilding(authored, entity, transform);
                    ApplyFactionColor(finished, entity);   // tints the Stripe_* accents
                    if (spawnsFinished)
                    {
                        // No construction phase: neutralize the sink/rise state the
                        // builder tail added so the tent stands complete at once.
                        var rise = finished.GetComponent<TheWaningBorder.Presentation.BuildingRiseData>();
                        if (rise != null) rise.ApplyRise(1f, 0f);
                    }
                    return finished;
                }

                // Unit tail: rotation/scale ride SyncTransforms; collider + link here.
                var scaleTag = authored.GetComponent<ProceduralScaleTag>();
                float baseScale = scaleTag != null && scaleTag.BaseScale > 0.001f ? scaleTag.BaseScale : 1f;
                authored.transform.localScale = Vector3.one * transform.Scale * baseScale;
                FitSelectionCollider(authored, entity, _em);
                var er = authored.GetComponent<EntityReference>();
                if (er == null) er = authored.AddComponent<EntityReference>();
                er.Entity = entity;
                return authored;
            }
        }

        // Units & standard buildings (Hall/Hut/Barracks/etc.) now get their visual
        // from the prefab on their SO (resolved by PresentationId via TechCatalog), with a
        // cube/capsule fallback — see the prefab resolution near the end of this method.
        // The walls / obstacles / veilstone-node / border-tile branches above keep their own
        // dedicated visuals.

        // === THE BORDER ground tiles: voxel-block cluster visual RETIRED
        // (2026-07-24). It was the OLD Border design's ground look (task-111);
        // under the Curse & Shardroot canon the cursed ground is painted
        // per-pixel by the TWB/Terrain/Lit curse overlay (InfluenceMaskTexture
        // masks), and the legacy blocks rendered as untextured checker slabs
        // on top of it. The sim entity keeps an invisible anchor GameObject
        // so cleanup/handoff paths stay untouched. ===
        if (presentationId == BorderGroundPresentationId)
        {
            var go = new GameObject("BorderGroundTile (visual retired)");
            go.transform.position = pos;
            return go;
        }

        // === CRYSTAL LOOT PILE (outcropping): procedural veilstone cluster on the ground ===
        if (presentationId == 301)
        {
            var go = CreateProceduralVeilstoneOutcroppingLoot(pos, entity);
            return go;
        }

        // === CRYSTAL NODES (buildings): procedural veilstone-themed visuals ===
        // Veilstone UNITS (320-322) use actual prefabs, so they fall through to prefab loading below
        if (presentationId == 310)
        {
            var go = CreateProceduralCrystalEntity(pos, presentationId, entity);
            AttachConstructionAnimation(go);
            return go;
        }

        // === PROCEDURAL BUILDINGS: culture-aware generated visuals ===
        // Determine faction culture for building tone
        // COMPLETED culture only (CultureConfig, not FactionColors): views
        // spawned during the 60s age-up research must stay neutral Lv0.
        byte buildingCulture = Cultures.None;
        if (_em.HasComponent<FactionTag>(entity))
        {
            var faction = _em.GetComponentData<FactionTag>(entity).Value;
            buildingCulture = CultureConfig.GetCompletedCulture(_em, faction);
        }

        // === BUILDING PREFABS (Hall / Barracks / Hut, level 0 OR 1) ===
        //
        // After age-up, all newly placed/spawned Hall/Barracks/Hut go straight
        // to the L1 culture prefab — no L0 visual flash during construction
        // followed by a 1-second delayed swap. Pre age-up, falls back to the
        // base prefab; if neither is present, falls through to procedural.
        //
        // The L1 path also stamps BuildingUpgradeState.Level=1 + applies the
        // L1 stat scaling so HP / train speed / attack rate match the
        // visual immediately. BuildingPrefabSwapSystem is told the entity
        // is already at L1 so it doesn't redundantly re-instantiate.
        {
            string buildingId = presentationId switch
            {
                100 => "Hall",
                102 => "Hut",
                510 => "Barracks",
                511 => "Barracks", // ArcheryRange reuses Barracks visual (copy-of-Barracks)
                _   => null,
            };

            GameObject buildingPrefab = null;
            byte spawnLevel = 0;

            // MULTI-VARIANT SO PREFAB WINS OUTRIGHT. One asset carries Lv0
            // plus every culture's Lv1-Lv3 and switches branches in place, so
            // there is nothing for the legacy per-level Resources reskin to
            // add — and letting that reskin go first actively broke things:
            // it is consulted BEFORE the SO prefab, so the moment a faction
            // had a culture, `Hall_al_1` shadowed freshly authored art and
            // the new prefab silently never spawned. Level is stamped here
            // exactly as the legacy L1 path does, so stats still match the
            // visual; FinishProceduralBuilding then reveals the culture
            // branch through BuildingVariantVisual.
            // Deliberately NOT gated on buildingId: that switch lists only the
            // four legacy-ladder ids, and the generic tail further down never
            // calls FinishProceduralBuilding — so a building outside the list
            // (the Royal Stable, and anything given multi-variant art later)
            // would spawn with no rise, no variant setup and no transition.
            // Any building whose SO prefab carries the layout belongs here.
            if (_em.HasComponent<BuildingTag>(entity)
                && TechCatalog.TryGetPrefab(presentationId, out var soVariantPrefab)
                && soVariantPrefab != null
                && TheWaningBorder.Presentation.BuildingVariantVisual.HasVariantLayout(soVariantPrefab))
            {
                buildingPrefab = soVariantPrefab;
                if (_em.HasComponent<FactionTag>(entity))
                {
                    var vFaction = _em.GetComponentData<FactionTag>(entity).Value;
                    if (CultureConfig.GetCompletedCulture(_em, vFaction) != Cultures.None)
                        spawnLevel = 1;
                }
            }

            // Try L1 first when faction has a culture.
            if (buildingPrefab == null && buildingId != null && _em.HasComponent<FactionTag>(entity))
            {
                var faction = _em.GetComponentData<FactionTag>(entity).Value;
                byte culture = CultureConfig.GetCompletedCulture(_em, faction);
                if (culture != Cultures.None && BuildingPrefabSwapSystem.Instance != null)
                {
                    int variant = (buildingId == "Hut") ? 1 + (Mathf.Abs(entity.Index) % 2) : 0;
                    buildingPrefab = BuildingPrefabSwapSystem.Instance.TryLoadLevel1Prefab(
                        buildingId, culture, variant, out _);
                    if (buildingPrefab != null) spawnLevel = 1;
                }
            }

            // SO-AUTHORED PREFAB (2026-07-13): the prefab assigned on the
            // building's ScriptableObject is the authoritative BASE visual.
            // It used to be consulted only in the generic tail, which this
            // branch returned before ever reaching — so a freshly assigned
            // SO prefab was silently shadowed by the legacy Resources model
            // ("I updated the SO but the game still uses the old prefab").
            // Priority: L1 culture reskin (age-up identity) > SO prefab >
            // legacy Resources base prefab.
            //
            // BUILDINGS ONLY: this block ends in FinishProceduralBuilding
            // (construction sink, building recolor, +180° rotation) and never
            // attaches UnitAnimationSync or the SO animator controller. Once
            // unit SOs started carrying prefabs, unqualified TryGetPrefab
            // routed every UNIT through here too — spawning them as inert
            // "buildings" with no animations. Units must fall through to the
            // generic tail below.
            if (buildingPrefab == null
                && _em.HasComponent<BuildingTag>(entity)
                && TechCatalog.TryGetPrefab(presentationId, out var soBuildingPrefab)
                && soBuildingPrefab != null)
            {
                buildingPrefab = soBuildingPrefab;
            }

            // Fall back to L0 base prefab.
            if (buildingPrefab == null)
                buildingPrefab = TryLoadBaseBuildingPrefab(presentationId);

            if (buildingPrefab != null)
            {
                // FinishProceduralBuilding writes the final visual rotation
                // (with the +180° building offset) — we just position here.
                var go = Instantiate(buildingPrefab, pos, Quaternion.identity);
                go.SetActive(true);
                StripThirdPartyControllers(go);
                // buildingId is null for variant-prefab buildings outside the
                // legacy four; fall back to the presentation id so the
                // hierarchy stays greppable instead of reading "Entity_7__L1".
                go.name = $"Entity_{entity.Index}_{buildingId ?? presentationId.ToString()}_L{spawnLevel}";
                // Preserve the prefab's authored scale through SyncTransforms.
                var ps = buildingPrefab.transform.localScale;
                float authoredScale = (ps.x + ps.y + ps.z) / 3f;
                float baseScale = authoredScale;
                // Snug-fit the visual to the building's grid footprint, folded
                // into BaseScale so SyncTransforms reapplies it every frame.
                // docs/Design/Build_Grid.md
                baseScale *= ComputeFootprintFit(go, entity, out Vector3 fitOffset);
                if (baseScale > 0.001f)
                {
                    var tag = go.AddComponent<ProceduralScaleTag>();
                    tag.BaseScale = baseScale;
                    tag.AuthoredScale = authoredScale;
                    tag.BaseOffset = fitOffset;
                    go.transform.localScale = Vector3.one * transform.Scale * baseScale;
                }
                var finished = FinishProceduralBuilding(go, entity, transform);

                // Presentation no longer stamps BuildingUpgradeState — that
                // is sim state (ApplyLevel writes Health.Max, which is in the
                // desync checksum) and a view spawn is render-paced, so the
                // stamp landed on different ticks per peer.
                // BuildingLevelOneSeedSystem now stamps it inside the tick;
                // this path only chooses the visual.
                if (spawnLevel == 1)
                {
                    // Null-guarded: the legacy path only ever set spawnLevel
                    // after proving the swap system exists, but the
                    // multi-variant path above sets it from the faction's
                    // culture alone and can run before that system spins up.
                    if (BuildingPrefabSwapSystem.Instance != null)
                        BuildingPrefabSwapSystem.Instance.RegisterPreSwapped(entity, finished, level: 1);
                }
                return finished;
            }
        }

        // Procedural unit/building generation has been removed — visuals now come from the
        // prefab referenced on the entity's SO (resolved by PresentationId via TechCatalog),
        // falling back to a primitive cube/capsule when no prefab is assigned.

        GameObject prefab = null;

        // Authoritative visual: the prefab referenced on this entity's SO (under GameData).
        // Null prefab (or no SO for this PresentationId) falls through to the ID-range
        // cube/capsule fallback below.
        if (TechCatalog.TryGetPrefab(presentationId, out var soPrefab))
            prefab = soPrefab;

        // (Legacy) culture-specific Resources override, kept as a secondary source.
        if (prefab == null &&
            CulturePrefabOverrides.TryGetValue((presentationId, buildingCulture), out string culturePath))
        {
            prefab = Resources.Load<GameObject>(culturePath);
        }

        // Default prefab for this presentation id
        if (prefab == null && PrefabPaths.TryGetValue(presentationId, out string path))
        {
            prefab = Resources.Load<GameObject>(path);
        }

        // Guaranteed primitive fallback (2026-07-13): CUBE for buildings,
        // CAPSULE for units — decided by the entity's actual components,
        // not the old ID-range guess (new PresentationIds outside the
        // 200-499 unit band were getting building cubes). ID range stays
        // as the tiebreak for entities carrying neither tag.
        if (prefab == null)
        {
            if (_em.HasComponent<UnitTag>(entity))
                prefab = _fallbackUnitPrefab;
            else if (_em.HasComponent<BuildingTag>(entity))
                prefab = _fallbackBuildingPrefab;
            else if (presentationId >= 200 && presentationId < 500)
                prefab = _fallbackUnitPrefab;
            else
                prefab = _fallbackBuildingPrefab;
        }

        if (prefab == null) return null;

        var goInst = Instantiate(prefab);
        goInst.SetActive(true); // Ensure active (fallback prefabs are stored inactive)
        StripThirdPartyControllers(goInst);
        goInst.name = $"Entity_{entity.Index}_{presentationId}";
        goInst.transform.position = pos;
        goInst.transform.rotation = VisualRotation(entity, transform.Rotation);
        // Preserve the prefab's authored root scale (FBX-variant prefabs often
        // carry a non-1 root scale). The placement preview instantiates the
        // same prefab as-is, so stomping the root with the bare ECS scale made
        // the built visual differ in size from its own preview. The
        // ProceduralScaleTag keeps SyncTransforms applying the same factor
        // every frame.
        {
            var authored = prefab.transform.localScale;
            float authoredUniform = (authored.x + authored.y + authored.z) / 3f;
            if (authoredUniform < 0.001f) authoredUniform = 1f;
            // Snug-fit sized buildings to their grid footprint. Returns 1 for
            // units, nodes and unsized buildings, so this is a no-op for them.
            // docs/Design/Build_Grid.md
            float authoredPreFit = authoredUniform;
            authoredUniform *= ComputeFootprintFit(goInst, entity, out Vector3 variantOffset);
            if (!Mathf.Approximately(authoredUniform, 1f) || variantOffset != Vector3.zero)
            {
                var scaleTag = goInst.GetComponent<ProceduralScaleTag>()
                            ?? goInst.AddComponent<ProceduralScaleTag>();
                scaleTag.BaseScale = authoredUniform;
                scaleTag.AuthoredScale = authoredPreFit;
                scaleTag.BaseOffset = variantOffset;
            }
            goInst.transform.localScale = Vector3.one * transform.Scale * authoredUniform;
        }

        // Selection collider — always refit to the visual's renderer bounds
        // so the click target matches the mesh. Prefab-authored colliders are
        // routinely mismatched (too big → block clicks on things behind; too
        // small / pivot-centered → half the box underground, hard to click).
        // Floored by the entity's sim footprint so it can never come out
        // smaller than the space the building actually occupies.
        FitSelectionCollider(goInst, entity, _em);

        // Add EntityReference for raycasting/selection
        var entityRef = goInst.GetComponent<EntityReference>();
        if (entityRef == null)
            entityRef = goInst.AddComponent<EntityReference>();
        entityRef.Entity = entity;

        // Attach VeilstingerGunTracker for Veilstinger units (PresentationId 321)
        // This rotates leftgun/rightgun children to LookAt their respective targets
        if (presentationId == 321)
        {
            var gunTracker = goInst.AddComponent<VeilstingerGunTracker>();
            gunTracker.Entity = entity;
        }

        // Attach UnitAnimationSync for units that have an Animator
        // (units have MoveSpeed, buildings don't)
        if (_em.HasComponent<MoveSpeed>(entity))
        {
            var animator = goInst.GetComponentInChildren<Animator>();
            if (animator != null)
            {
                var animSync = goInst.AddComponent<UnitAnimationSync>();
                animSync.LinkedEntity = entity;

                // If the prefab's Animator has no controller of its own (e.g. a
                // prefab that is a variant of a character FBX — its inherited
                // Animator ships without one), assign the controller authored on
                // the unit's SO. Set BEFORE UnitAnimationSync.Start() runs, so its
                // parameter probe sees the controller's parameters. Units whose
                // prefab already bakes in a controller (e.g. Longbowman) keep it.
                if (animator.runtimeAnimatorController == null &&
                    TechCatalog.TryGetController(presentationId, out var soController))
                {
                    animator.runtimeAnimatorController = soController;
                }

                if (presentationId == LongbowmanPresentationId)
                {
                    // Sync the draw→shoot cycle to the unit's fire rate so
                    // exactly one cycle plays per arrow (not ~1.5).
                    animSync.AttackCycleSeconds = LongbowmanAttackCycleSeconds;
                }

                // Longbowman corpses linger in their final death pose then
                // dissolve out, rather than popping out of existence. The
                // component stays dormant until CleanupDestroyedEntities hands it
                // the GameObject on entity destruction (BeginDeath).
                if (presentationId == LongbowmanPresentationId)
                {
                    goInst.AddComponent<CorpseDissolver>();
                }
            }
        }

        // Apply faction coloring
        ApplyFactionColor(goInst, entity);

        // Progressive battle-damage shader for buildings that spawn via the
        // generic prefab path (those that don't go through FinishProceduralBuilding).
        if (_em.HasComponent<BuildingTag>(entity))
        {
            var dmgVis = goInst.GetComponent<TheWaningBorder.Presentation.BuildingDamageVisual>()
                      ?? goInst.AddComponent<TheWaningBorder.Presentation.BuildingDamageVisual>();
            dmgVis.Entity = entity;

            // Team-color the atlas: blue-painted regions -> faction color.
            // FinishProceduralBuilding does this for its path; the generic
            // SO-prefab path never did, so prefab buildings kept their
            // authored blue roofs/trim regardless of owner.
            if (_em.HasComponent<FactionTag>(entity))
            {
                var fac = _em.GetComponentData<FactionTag>(entity).Value;
                BuildingFactionColorMarker.Apply(goInst, FactionColors.Get(fac));
            }

            // Construction rise: sink depth from ACTUAL renderer bounds + the
            // per-piece rise snapshot. This generic prefab path never attached
            // these, so SyncTransforms fell back to a Radius*2 sink — any
            // building mesh taller than that poked its roof above the ground
            // at construction progress 0. Must run after position/scale are
            // final (bounds are world-space).
            AttachConstructionAnimation(goInst);
        }

        return goInst;
    }

    private void ApplyFactionColor(GameObject go, Entity entity)
    {
        if (!_em.HasComponent<FactionTag>(entity)) return;

        var faction = _em.GetComponentData<FactionTag>(entity).Value;
        var color = FactionColors.Get(faction); // Returns culture color if faction has aged up

        bool isBuilding = _em.HasComponent<BuildingTag>(entity);

        if (isBuilding)
        {
            // Single source of truth for the building faction-color rule
            // (roof / stripe / atlas swap). This used to be a second, divergent
            // copy of the roof+stripe rule that lived only here — so any visual
            // produced outside PresentationSpawnSystem (notably the upgrade
            // prefab swap) never got it and kept an authored blue roof.
            BuildingFactionColorMarker.Apply(go, color);
        }
        // Units keep their authored prefab materials untinted. Team ownership
        // reads through selection rings, health bars, and the minimap instead.
        // (The old whole-body wash / Synty atlas team-region recolor was removed
        // here — it flattened the real character models wired from the KI and
        // ExplosiveLLC packs into a single flat colour.)
    }

    /// <summary>
    /// Finish setting up a procedurally generated building: collider, EntityReference,
    /// transform sync, and faction coloring. Mirrors the setup done for prefab-based buildings.
    /// </summary>
    private GameObject FinishProceduralBuilding(GameObject go, Entity entity, LocalTransform transform)
    {
        go.name = $"Entity_{entity.Index}_{(_em.HasComponent<PresentationId>(entity) ? _em.GetComponentData<PresentationId>(entity).Id : 0)}";
        go.transform.rotation = VisualRotation(entity, transform.Rotation);
        // Keep the authored root scale that the caller already applied
        // (ProceduralScaleTag.BaseScale for FBX-variant prefabs). This used to
        // assign `Vector3.one * transform.Scale`, dropping BaseScale — so the
        // collider below was fitted at a scale the visual does not run at.
        {
            var scaleTag = go.GetComponent<ProceduralScaleTag>();
            float baseScale = scaleTag != null && scaleTag.BaseScale > 0.001f ? scaleTag.BaseScale : 1f;
            go.transform.localScale = Vector3.one * transform.Scale * baseScale;
        }

        // Aggregate selection collider fitted to the actual visual bounds
        // (shared fitter — also clears the same-frame-queryable colliders the
        // Prim helpers destroyed), floored by the entity's sim footprint.
        FitSelectionCollider(go, entity, _em);

        // Cache the visual extent so SyncTransforms can sink the building
        // fully underground during construction. Pivot may sit above the
        // ground (authored prefabs often anchor at base centre, but some
        // sit higher), so include any positive max-y on top of size.y.
        {
            var renderers = go.GetComponentsInChildren<Renderer>();
            if (renderers.Length > 0)
            {
                var bounds = renderers[0].bounds;
                for (int r = 1; r < renderers.Length; r++)
                    bounds.Encapsulate(renderers[r].bounds);

                float visualHeight = bounds.size.y +
                    Mathf.Max(0f, bounds.max.y - go.transform.position.y);
                if (visualHeight > 0f)
                {
                    var sink = go.GetComponent<TheWaningBorder.Presentation.BuildingVisualSinkDepth>()
                            ?? go.AddComponent<TheWaningBorder.Presentation.BuildingVisualSinkDepth>();
                    sink.Value = visualHeight + 0.5f; // small pad keeps the tip below
                }
            }
        }

        // EntityReference for raycasting/selection
        var entityRef = go.GetComponent<EntityReference>();
        if (entityRef == null) entityRef = go.AddComponent<EntityReference>();
        entityRef.Entity = entity;

        // Authored prefabs paint team-color regions with a flat marker hue
        // (default pure blue). Replace with the faction color at runtime so
        // each player's buildings carry their lobby color. Procedural
        // buildings have no marker materials so this is a no-op for them.
        if (_em.HasComponent<FactionTag>(entity))
        {
            var fac = _em.GetComponentData<FactionTag>(entity).Value;
            BuildingFactionColorMarker.Apply(go, FactionColors.Get(fac));
        }

        // Multi-variant authored prefabs (Lv0 + per-culture Lv1-Lv3 inside
        // one prefab): hide the culture branches so construction always
        // shows the numbered Lv0 model. Must run BEFORE the rise snapshot.
        var variant = TheWaningBorder.Presentation.BuildingVariantVisual.TrySetup(go);

        // Buildings whose art ships an A and a B shape per level (huts and
        // houses) resolve to one of them here. Keyed off the entity index so
        // the choice is identical on every lockstep peer and stable for the
        // life of the building. Must run BEFORE the rise snapshot so the
        // discarded shape never joins the construction pieces.
        TheWaningBorder.Presentation.BuildingAbVariantPicker.Apply(go, entity.Index);

        // Snapshot the visual hierarchy for the staggered construction rise.
        // Done last so any runtime-attached helpers are included in the pieces.
        var rise = go.GetComponent<TheWaningBorder.Presentation.BuildingRiseData>()
                ?? go.AddComponent<TheWaningBorder.Presentation.BuildingRiseData>();
        rise.Init();

        // Spawned already complete (starting buildings, mid-game joins):
        // jump straight to the culture model when a culture is chosen.
        if (variant != null && !_em.HasComponent<UnderConstruction>(entity)
            && _em.HasComponent<FactionTag>(entity))
        {
            var vFac = _em.GetComponentData<FactionTag>(entity).Value;
            byte vCulture = CultureConfig.GetCompletedCulture(_em, vFac);
            int vLevel = _em.HasComponent<BuildingUpgradeState>(entity)
                ? Mathf.Max(1, _em.GetComponentData<BuildingUpgradeState>(entity).Level)
                : 1;
            if (variant.ShowVariant(vCulture, vLevel))
                BuildingFactionColorMarker.Apply(go, FactionColors.Get(vFac));
            variant.SyncTechVisuals(vFac, FactionColors.Get(vFac), withTransition: false);
            // Different branch = different art: re-derive fit and centring.
            RefitVariantView(go, entity, _em);
        }

        // Progressive battle-damage shader, driven from the entity's Health. It
        // stays dormant (original materials untouched) until the building first
        // takes damage. Guarded to true buildings so resource/veilstone nodes that
        // also route through here keep their own shaders.
        if (_em.HasComponent<BuildingTag>(entity))
        {
            var dmgVis = go.GetComponent<TheWaningBorder.Presentation.BuildingDamageVisual>()
                      ?? go.AddComponent<TheWaningBorder.Presentation.BuildingDamageVisual>();
            dmgVis.Entity = entity;
        }

        return go;
    }

    /// <summary>
    /// Attach the sink-depth tag (sized to actual renderer bounds) and the
    /// rise-animation snapshot to a procedural visual that doesn't pass
    /// through FinishProceduralBuilding — walls, towers, gates, smelter,
    /// border nodes. Idempotent: safe to call repeatedly.
    /// </summary>
    private static void AttachConstructionAnimation(GameObject go)
    {
        if (go == null) return;

        var renderers = go.GetComponentsInChildren<Renderer>();
        if (renderers.Length > 0)
        {
            var bounds = renderers[0].bounds;
            for (int r = 1; r < renderers.Length; r++)
                bounds.Encapsulate(renderers[r].bounds);
            float visualHeight = bounds.size.y +
                Mathf.Max(0f, bounds.max.y - go.transform.position.y);
            if (visualHeight > 0f)
            {
                var sink = go.GetComponent<TheWaningBorder.Presentation.BuildingVisualSinkDepth>()
                        ?? go.AddComponent<TheWaningBorder.Presentation.BuildingVisualSinkDepth>();
                sink.Value = visualHeight + 0.5f;
            }
        }

        var rise = go.GetComponent<TheWaningBorder.Presentation.BuildingRiseData>()
                ?? go.AddComponent<TheWaningBorder.Presentation.BuildingRiseData>();
        rise.Init();
    }

    // ──────────────────────────────────────────────────────────────────
    // BASE BUILDING PREFAB LOOKUP (Hall / Barracks / Hut / GatherersHut, level 0)
    // ──────────────────────────────────────────────────────────────────

    // Cached Resources lookups so we don't re-resolve every spawn. null
    // entries mean "negative cache — no prefab exists at this path".
    private readonly System.Collections.Generic.Dictionary<int, GameObject> _baseBuildingPrefabCache = new();
    private readonly System.Collections.Generic.HashSet<int> _baseBuildingPrefabNegativeCache = new();

    /// <summary>
    /// Look up the level-0 hand-authored prefab for Hall / Barracks / Hut / GatherersHut.
    /// Returns null if no prefab is present at the canonical path — caller
    /// falls back to procedural generation.
    /// </summary>
    private GameObject TryLoadBaseBuildingPrefab(int presentationId)
    {
        if (_baseBuildingPrefabCache.TryGetValue(presentationId, out var cached))
            return cached;
        if (_baseBuildingPrefabNegativeCache.Contains(presentationId)) return null;

        string path = presentationId switch
        {
            100 => "Prefabs/Buildings/Hall",         // Hall.PresentationID
            101 => "Prefabs/Buildings/GatherersHut", // GatherersHut.PresentationID — single prefab, no culture/level variants
            102 => "Prefabs/Buildings/Hut",          // Hut.PresentationID
            510 => "Prefabs/Buildings/Barracks",     // Barracks.PresentationID
            511 => "Prefabs/Buildings/Barracks",     // ArcheryRange reuses Barracks visual
            _   => null,
        };
        if (path == null)
        {
            _baseBuildingPrefabNegativeCache.Add(presentationId);
            return null;
        }

        var loaded = Resources.Load<GameObject>(path);
        if (loaded == null)
        {
            _baseBuildingPrefabNegativeCache.Add(presentationId);
            return null;
        }
        _baseBuildingPrefabCache[presentationId] = loaded;
        return loaded;
    }

    // EnsureBuildingUpgradeStateAtLevel1 removed (2026-08-16): stamping
    // BuildingUpgradeState + ApplyLevel from presentation code was a
    // determinism bug — see BuildingLevelOneSeedSystem for the sim-side
    // replacement and the full rationale.

    /// <summary>
    /// Finish setting up a procedurally generated unit: collider, EntityReference,
    /// transform sync, and faction coloring.
    /// </summary>
    private GameObject FinishProceduralUnit(GameObject go, Entity entity, int presentationId, LocalTransform transform)
    {
        go.name = $"Entity_{entity.Index}_{presentationId}";
        go.transform.rotation = transform.Rotation;

        // Apply ECS scale multiplied by procedural base scale
        var scaleTag = go.GetComponent<ProceduralScaleTag>();
        float baseScale = (scaleTag != null) ? scaleTag.BaseScale : 1f;
        go.transform.localScale = Vector3.one * transform.Scale * baseScale;

        // Selection collider fitted to the unit's visual bounds, floored by the
        // unit's own Radius so slim models stay comfortably clickable.
        FitSelectionCollider(go, entity, _em);

        // EntityReference for raycasting/selection
        var entityRef = go.GetComponent<EntityReference>();
        if (entityRef == null) entityRef = go.AddComponent<EntityReference>();
        entityRef.Entity = entity;

        // Attach VeilstingerGunTracker for Veilstinger units
        if (presentationId == 321)
        {
            var gunTracker = go.AddComponent<VeilstingerGunTracker>();
            gunTracker.Entity = entity;
        }

        // Apply faction coloring (overwrites white/neutral parts with faction color)
        ApplyFactionColor(go, entity);

        return go;
    }

    // Faction banner pole/flag REMOVED (2026-07-15, user request): ownership
    // reads through team-color regions, selection rings, and the minimap.

    /// <summary>
    /// Reapply faction colors to all visuals belonging to a faction.
    /// Called after age-up to refresh culture colors on existing entities.
    /// </summary>
    public void RefreshFactionColors(Faction faction)
    {
        if (EntityViewManager.Instance == null) return;

        var entities = _presentationQuery.ToEntityArray(Unity.Collections.Allocator.Temp);

        for (int i = 0; i < entities.Length; i++)
        {
            var entity = entities[i];
            if (!_em.HasComponent<FactionTag>(entity)) continue;
            if (_em.GetComponentData<FactionTag>(entity).Value != faction) continue;

            if (EntityViewManager.Instance.TryGetView(entity, out var go) && go != null)
            {
                ApplyFactionColor(go, entity);
            }
        }

        entities.Dispose();
    }

    /// <summary>
    /// Rebuild all building visuals for a faction with culture-aware procedural generation.
    /// Called after age-up completion to retrofit existing Era 1 buildings with culture tone.
    /// </summary>
    public void RefreshFactionVisuals(Faction faction)
    {
        if (EntityViewManager.Instance == null) return;

        byte culture = CultureConfig.GetCompletedCulture(_em, faction);

        var entities = _presentationQuery.ToEntityArray(Unity.Collections.Allocator.Temp);
        var presentations = _presentationQuery.ToComponentDataArray<PresentationId>(Unity.Collections.Allocator.Temp);
        var transforms = _presentationQuery.ToComponentDataArray<LocalTransform>(Unity.Collections.Allocator.Temp);

        for (int i = 0; i < entities.Length; i++)
        {
            var entity = entities[i];
            if (!_em.HasComponent<FactionTag>(entity)) continue;
            if (_em.GetComponentData<FactionTag>(entity).Value != faction) continue;
            if (!_em.HasComponent<BuildingTag>(entity)) continue;

            int pid = presentations[i].Id;

            // Procedural generation has been removed — there are no procedural variants.
            // A culture-aware rebuild is only needed for a culture-specific prefab override.
            bool hasProceduralVariant = false;
            bool hasCultureOverride = CulturePrefabOverrides.ContainsKey((pid, culture));

            if (!hasProceduralVariant && !hasCultureOverride)
            {
                // No culture-specific visual for this building — just refresh colors.
                if (EntityViewManager.Instance.TryGetView(entity, out var existGo) && existGo != null)
                    ApplyFactionColor(existGo, entity);
                continue;
            }

            // Capture the old visual for the dissolve transition (if any).
            // Do NOT destroy it here — BuildingDissolveTransition takes
            // ownership and destroys it once the wave completes.
            GameObject oldGo = null;
            if (EntityViewManager.Instance.TryGetView(entity, out var existing) && existing != null)
            {
                oldGo = existing;
                EntityViewManager.Instance.UnregisterView(entity);
                _spawnedEntities.Remove(entity);
            }

            // Respawn through the canonical entry point so procedural and
            // prefab-override paths both go through the same setup (colliders,
            // EntityReference, faction coloring).
            var newGo = SpawnVisual(entity, pid, transforms[i]);
            if (newGo != null)
            {
                EntityViewManager.Instance.RegisterView(entity, newGo);
                _spawnedEntities.Add(entity);

                // Wave dissolve from old culture-neutral visual to the new
                // culture-specific one. Faction-tinted edge glow.
                Color accent = FactionColors.Get(faction);
                BuildingDissolveTransition.Begin(oldGo, newGo, duration: 1.5f, edgeColor: accent);
            }
            else if (oldGo != null)
            {
                // No new visual was produced — keep the old one rather than
                // leaving the entity invisible.
                EntityViewManager.Instance.RegisterView(entity, oldGo);
                _spawnedEntities.Add(entity);
            }
        }

        entities.Dispose();
        presentations.Dispose();
        transforms.Dispose();

    }

    private void SyncTransforms()
    {
        if (EntityViewManager.Instance == null) return;

        var entities = _presentationQuery.ToEntityArray(Unity.Collections.Allocator.Temp);
        var transforms = _presentationQuery.ToComponentDataArray<LocalTransform>(Unity.Collections.Allocator.Temp);

        var em = World.DefaultGameObjectInjectionWorld?.EntityManager;

        // Under lockstep the simulation advances in fixed steps, so transforms
        // arrive in discrete jumps and views have to be interpolated between
        // them or the whole game reads as though it ran at the tick rate.
        bool interpolate = TheWaningBorder.Core.Multiplayer.LockstepTiming.FixedStepActive;
        float stepDuration = Mathf.Max(
            0.0001f, TheWaningBorder.Core.Multiplayer.LockstepTiming.TickDuration);

        for (int i = 0; i < entities.Length; i++)
        {
            if (EntityViewManager.Instance.TryGetView(entities[i], out var go) && go != null)
            {
                // ── Per-view cache (see ViewSync) ────────────────────────
                if (!_viewSync.TryGetValue(entities[i], out var sync))
                {
                    sync = new ViewSync();
                    _viewSync[entities[i]] = sync;
                }
                if (sync.View != go)
                {
                    sync.View = go;
                    sync.ScaleTag = go.GetComponent<ProceduralScaleTag>();
                    sync.Rise = go.GetComponent<TheWaningBorder.Presentation.BuildingRiseData>();
                    sync.Primed = false;   // new view: force a full write
                }

                bool underConstruction = em.HasValue
                    && em.Value.HasComponent<UnderConstruction>(entities[i]);

                // Static-entity fast path: nothing about this visual changed
                // since the last sync, so skip the terrain sample and the
                // three transform writes entirely. Under-construction visuals
                // never take it — their rise animation advances every frame.
                // Nor does a view still playing out an interpolation segment.
                if (sync.Primed && !underConstruction && !sync.LastUnderConstruction
                    && sync.LastTerrainVersion == TerrainUtility.TerrainVersion
                    && sync.LastPos.Equals(transforms[i].Position)
                    && sync.LastRot.value.Equals(transforms[i].Rotation.value)
                    && sync.LastScale == transforms[i].Scale
                    && (!interpolate || sync.SegmentT >= 1f))
                    continue;

                var simPos = transforms[i].Position;
                var simRot = VisualRotation(entities[i], transforms[i].Rotation);

                if (interpolate)
                {
                    // A changed simulated transform opens a new segment, played
                    // out over one tick's worth of real time. Starting it from
                    // where the view actually IS (not from the previous
                    // simulated value) keeps the motion continuous even when a
                    // frame is long enough to span two ticks.
                    if (!sync.Primed
                        || !sync.LastPos.Equals(simPos)
                        || !sync.LastRot.value.Equals(transforms[i].Rotation.value))
                    {
                        bool teleport = !sync.Primed
                            || Unity.Mathematics.math.distancesq(sync.RenderPos, simPos) > TeleportSnapDistanceSq;

                        sync.FromPos = teleport ? simPos : sync.RenderPos;
                        sync.FromRot = teleport ? simRot : sync.RenderRot;
                        sync.ToPos = simPos;
                        sync.ToRot = simRot;
                        sync.SegmentT = teleport ? 1f : 0f;
                    }

                    sync.SegmentT = Mathf.Min(1f, sync.SegmentT + Time.deltaTime / stepDuration);
                    sync.RenderPos = Unity.Mathematics.math.lerp(sync.FromPos, sync.ToPos, sync.SegmentT);
                    sync.RenderRot = Quaternion.Slerp(sync.FromRot, sync.ToRot, sync.SegmentT);
                }
                else
                {
                    sync.RenderPos = simPos;
                    sync.RenderRot = simRot;
                    sync.SegmentT = 1f;
                }

                var pos = (Vector3)sync.RenderPos;
                // Nearest walking surface to the SIMULATED Y — keeps visuals
                // on the bridge deck when the entity is on a bridge, and on
                // the ground when it walks under one. Sampled at the RENDERED
                // x/z so a unit crossing a slope rides it smoothly rather than
                // in tick-sized steps.
                pos.y = TerrainUtility.GetSurfaceHeight(pos.x, pos.z, sync.RenderPos.y);

                // Construction rising animation: pieces start below ground and
                // rise into place bottom-to-top via BuildingRiseData. Falls back
                // to a rigid root sink for visuals that don't have rise data
                // attached (e.g. mid-construction prefab swap before re-init).
                if (underConstruction)
                {
                    var uc = em.Value.GetComponentData<UnderConstruction>(entities[i]);
                    float ratio = uc.Total > 0 ? Mathf.Clamp01(uc.Progress / uc.Total) : 1f;
                    var sinkTag = go.GetComponent<TheWaningBorder.Presentation.BuildingVisualSinkDepth>();
                    float sinkDepth = (sinkTag != null && sinkTag.Value > 0f)
                        ? sinkTag.Value
                        : (em.Value.HasComponent<Radius>(entities[i])
                            ? em.Value.GetComponentData<Radius>(entities[i]).Value * 2f
                            : 3f);

                    var rise = sync.Rise;
                    if (rise != null && rise.HasPieces)
                        rise.ApplyRise(ratio, sinkDepth);
                    else
                        // Rigid root sink — also the path for single-mesh
                        // prefabs whose only renderer sits on the root (no
                        // child pieces to stagger).
                        pos.y -= sinkDepth * (1f - ratio);
                }
                else
                {
                    // Just exited UnderConstruction: snap pieces back to rest
                    // once and fire the same flourish used for level-up swaps
                    // so the transition reads clearly to the player.
                    var rise = sync.Rise;
                    if (rise != null && rise.NotifyConstructionComplete())
                    {
                        Color accent = new Color(1f, 0.85f, 0.45f);
                        if (em.HasValue && em.Value.HasComponent<FactionTag>(entities[i]))
                        {
                            var cFac = em.Value.GetComponentData<FactionTag>(entities[i]).Value;
                            accent = FactionColors.Get(cFac);

                            // Culture already chosen: the finished building
                            // transitions to its culture Lv1 model right away
                            // (multi-variant prefabs only) using the same
                            // dissolve wave as the Hall's level-up swaps.
                            var cVariant = go.GetComponent<TheWaningBorder.Presentation.BuildingVariantVisual>();
                            if (cVariant != null)
                            {
                                byte cCulture = CultureConfig.GetCompletedCulture(_em, cFac);
                                cVariant.ShowVariantWithTransition(cCulture, 1, accent);
                                // Already-earned tech visuals appear as part
                                // of the reveal, not as separate waves.
                                cVariant.SyncTechVisuals(cFac, accent, withTransition: false);
                                // The culture branch is different art from
                                // the Lv0 the fit was measured on.
                                RefitVariantView(go, entities[i], em.Value);
                            }
                        }
                        TheWaningBorder.Presentation.BuildingLevelUpEffect.Spawn(go, accent);
                    }
                }

                // Respect procedural unit base scale (ProceduralScaleTag)
                float baseScale = (sync.ScaleTag != null) ? sync.ScaleTag.BaseScale : 1f;
                float finalScale = transforms[i].Scale * baseScale;

                // Pivot-offset compensation: shift the root so the SCALED
                // bounds centre — not the prefab pivot — sits on the entity
                // position. Rotates with the view. Zero for units and
                // procedural builders (see ProceduralScaleTag.BaseOffset).
                if (sync.ScaleTag != null && sync.ScaleTag.BaseOffset != Vector3.zero)
                    pos -= (sync.RenderRot * sync.ScaleTag.BaseOffset) * finalScale;

                go.transform.position = pos;
                go.transform.rotation = sync.RenderRot;
                go.transform.localScale = Vector3.one * finalScale;

                sync.LastPos = transforms[i].Position;
                sync.LastRot = transforms[i].Rotation;
                sync.LastScale = transforms[i].Scale;
                sync.LastUnderConstruction = underConstruction;
                sync.LastTerrainVersion = TerrainUtility.TerrainVersion;
                sync.Primed = true;
            }
        }

        entities.Dispose();
        transforms.Dispose();
    }

    private GameObject CreateFallbackPrefab(string name, PrimitiveType type, float scale)
    {
        var go = GameObject.CreatePrimitive(type);
        go.name = name;
        go.transform.localScale = Vector3.one * scale;
        go.SetActive(false); // Hide the template
        DontDestroyOnLoad(go);
        return go;
    }

    private Color GetFactionColor(Faction faction)
    {
        return faction switch
        {
            Faction.Blue => new Color(0.3f, 0.5f, 1f),
            Faction.Red => new Color(1f, 0.3f, 0.3f),
            Faction.Green => new Color(0.3f, 1f, 0.3f),
            Faction.Yellow => new Color(1f, 1f, 0.3f),
            Faction.Purple => new Color(0.8f, 0.3f, 1f),
            Faction.Orange => new Color(1f, 0.6f, 0.2f),
            Faction.Teal => new Color(0.2f, 0.8f, 0.8f),
            Faction.White => new Color(0.9f, 0.9f, 0.9f),
            Faction.Border => new Color(0.6f, 0.85f, 0.95f), // icy cyan — veilstone aesthetic
            _ => Color.gray
        };
    }


    /// <summary>
    /// Fit ONE root BoxCollider to the combined renderer bounds of the visual
    /// so the click target matches what the player actually sees. Every other
    /// collider under the root is removed — presentation colliders exist ONLY
    /// for selection raycasts, and prefab-authored ones are routinely wrong
    /// (oversized loot boxes block clicks; undersized unit boxes make units
    /// like the Veilstinger nearly unclickable). Bounds are stored in
    /// root-LOCAL space so later uniform scaling (ECS scale x
    /// ProceduralScaleTag) keeps collider and mesh matched. The min* floors
    /// (world units at fit time) keep slim visuals comfortably clickable.
    /// </summary>
    /// <summary>
    /// Entity-aware wrapper: fits to the renderer bounds as usual, but never
    /// smaller than the entity's SIMULATION footprint.
    ///
    /// Renderer bounds alone are not a trustworthy click target. They are
    /// measured at whatever scale the visual happens to hold at fit time, they
    /// exclude anything inactive, and for FBX-variant prefabs they can be a
    /// fraction of the space the building actually occupies — the Hall (a 4x4
    /// footprint in the sim) ended up with a box barely a metre across and was
    /// nearly unclickable. The sim already knows how big each entity is, via
    /// BuildingSize or Radius; that is the authority for how big its click
    /// target must be, so use it as a floor.
    /// </summary>
    internal static BoxCollider FitSelectionCollider(GameObject root, Entity entity, EntityManager em,
        float minWorldXZ = 0.9f, float minWorldY = 1.0f)
    {
        if (em.Exists(entity))
        {
            if (em.HasComponent<BuildingSize>(entity))
            {
                // Grid cells are 1 m. Floor both axes by the SHORT side so the
                // box stays correct whichever way the building is rotated.
                var bs = em.GetComponentData<BuildingSize>(entity);
                minWorldXZ = Mathf.Max(minWorldXZ, Mathf.Min(bs.Width, bs.Height));
                minWorldY = Mathf.Max(minWorldY, 2.0f); // buildings are never ankle-high
            }
            else if (em.HasComponent<Radius>(entity))
            {
                minWorldXZ = Mathf.Max(minWorldXZ, em.GetComponentData<Radius>(entity).Value * 2f);
            }
        }

        return FitSelectionCollider(root, minWorldXZ, minWorldY);
    }

    /// <summary>
    /// Replace every collider on a visual with ONE axis-aligned box that fills
    /// exactly the build cell the entity occupies — a 2 m cube standing on the
    /// ground, not a box shrink-wrapped to the art.
    ///
    /// Mesh-fitted boxes (<see cref="FitSelectionCollider"/>) are wrong for
    /// one-cell resource nodes: the gem-cluster art is a ragged clump that
    /// under-fills its cell in some directions and pokes past it in others, so
    /// the click target and the ground the node actually blocks disagree. A
    /// cell-sized cube makes selection, the impassable cell, and the sim
    /// <see cref="Radius"/> all describe the same square.
    ///
    /// <paramref name="worldScaleFactor"/> is the visual's eventual UNIFORM
    /// world scale (ECS <c>LocalTransform.Scale</c> × <see cref="ProceduralScaleTag.BaseScale"/>
    /// — see SyncTransforms). BoxCollider.size is local, so the world size is
    /// divided back out here; reading transform.lossyScale instead would be
    /// wrong, because SyncTransforms has not applied the scale yet at spawn.
    /// docs/Design/Build_Grid.md
    /// </summary>
    /// <summary>
    /// The uniform world scale a visual will end up at once SyncTransforms runs
    /// (entity <c>LocalTransform.Scale</c> × the prefab's
    /// <see cref="ProceduralScaleTag.BaseScale"/>). Feed this to
    /// <see cref="FitCellBoxCollider"/>: at spawn the transform has not been
    /// scaled yet, so reading lossyScale there gives the wrong answer.
    /// </summary>
    private float CellColliderScaleFor(Entity entity, float baseScale)
    {
        float ecsScale = 1f;
        if (_em.Exists(entity) && _em.HasComponent<Unity.Transforms.LocalTransform>(entity))
        {
            float s = _em.GetComponentData<Unity.Transforms.LocalTransform>(entity).Scale;
            if (s > 1e-4f) ecsScale = s;
        }
        return ecsScale * baseScale;
    }

    internal static BoxCollider FitCellBoxCollider(GameObject root,
        float worldScaleFactor, float worldHeight = 2f)
    {
        BoxCollider col = null;
        var existing = root.GetComponentsInChildren<Collider>(true);
        for (int i = 0; i < existing.Length; i++)
        {
            var c = existing[i];
            if (col == null && c.gameObject == root && c is BoxCollider bc) { col = bc; continue; }
            Object.Destroy(c);
        }
        if (col == null) col = root.AddComponent<BoxCollider>();

        float s = Mathf.Abs(worldScaleFactor) > 1e-4f ? Mathf.Abs(worldScaleFactor) : 1f;
        col.size = new Vector3(BuildGrid.CellSize, worldHeight, BuildGrid.CellSize) / s;
        col.center = new Vector3(0f, worldHeight * 0.5f, 0f) / s;
        return col;
    }

    internal static BoxCollider FitSelectionCollider(GameObject root,
        float minWorldXZ = 0.9f, float minWorldY = 1.0f)
    {
        // Drop every existing collider; keep (reuse) a root BoxCollider if
        // one is already there. Destroyed colliders linger queryable until
        // end of frame — harmless, the fitted box takes over afterwards.
        BoxCollider col = null;
        var existing = root.GetComponentsInChildren<Collider>(true);
        for (int i = 0; i < existing.Length; i++)
        {
            var c = existing[i];
            if (col == null && c.gameObject == root && c is BoxCollider bc) { col = bc; continue; }
            Object.Destroy(c);
        }
        if (col == null) col = root.AddComponent<BoxCollider>();

        // Combined renderer bounds in root-local space (world AABB corners
        // inverse-transformed, so child rotations are handled). Particle /
        // trail / line renderers are skipped — their bounds balloon.
        //
        // ACTIVE renderers only: Renderer.bounds on a disabled object is not
        // maintained, and multi-variant building prefabs ship with every
        // culture/level branch deactivated. Folding their stale (often
        // origin-centred) bounds in either ballooned the box across the map or
        // dragged its centre off the model. Fall back to including inactive ones
        // only when nothing is active, which is better than no bounds at all.
        bool has = false;
        Vector3 min = Vector3.zero, max = Vector3.zero;
        var renderers = root.GetComponentsInChildren<Renderer>(false);
        if (renderers.Length == 0) renderers = root.GetComponentsInChildren<Renderer>(true);
        for (int i = 0; i < renderers.Length; i++)
        {
            var r = renderers[i];
            if (r is ParticleSystemRenderer || r is TrailRenderer || r is LineRenderer) continue;
            var b = r.bounds;
            for (int k = 0; k < 8; k++)
            {
                var corner = new Vector3(
                    (k & 1) == 0 ? b.min.x : b.max.x,
                    (k & 2) == 0 ? b.min.y : b.max.y,
                    (k & 4) == 0 ? b.min.z : b.max.z);
                var lp = root.transform.InverseTransformPoint(corner);
                if (!has) { min = lp; max = lp; has = true; }
                else { min = Vector3.Min(min, lp); max = Vector3.Max(max, lp); }
            }
        }

        Vector3 center, size;
        if (has)
        {
            center = (min + max) * 0.5f;
            size = max - min;
        }
        else
        {
            // No renderers (yet) — 1m box above the pivot as a stopgap.
            center = Vector3.up * 0.5f;
            size = Vector3.one;
        }

        // Minimum click size, converted from world to local units.
        var ls = root.transform.lossyScale;
        float sx = Mathf.Abs(ls.x) > 1e-4f ? Mathf.Abs(ls.x) : 1f;
        float sy = Mathf.Abs(ls.y) > 1e-4f ? Mathf.Abs(ls.y) : 1f;
        float sz = Mathf.Abs(ls.z) > 1e-4f ? Mathf.Abs(ls.z) : 1f;
        size.x = Mathf.Max(size.x, minWorldXZ / sx);
        size.y = Mathf.Max(size.y, minWorldY / sy);
        size.z = Mathf.Max(size.z, minWorldXZ / sz);

        col.center = center;
        col.size = size;
        return col;
    }




    void OnDestroy()
    {
        // Clean up fallback prefabs
        if (_fallbackUnitPrefab != null) Destroy(_fallbackUnitPrefab);
        if (_fallbackBuildingPrefab != null) Destroy(_fallbackBuildingPrefab);

        if (Instance == this) Instance = null;
    }
}