// CrystalComponents.cs
// Components specific to the Crystal enemy faction
// Place in: Assets/Scripts/Core/Components/Crystal/

using Unity.Entities;
using Unity.Mathematics;

// ==================== Crystal Entity Tags ====================

/// <summary>Marks an entity as belonging to the Crystal faction.</summary>
public struct CrystalTag : IComponentData { }

/// <summary>Marks ground as corrupted by Crystal spread.</summary>
public struct CursedGroundTag : IComponentData { }

/// <summary>Identifies main Crystal hives.</summary>
public struct CrystalMainNodeTag : IComponentData { }

/// <summary>Sub-node types for Crystal structures.</summary>
public enum CrystalSubNodeType : byte
{
    Resource,
    Enforcer,
    Repair,
    Turret,
    Nexus,
    Ward,
    Storm,
    Obelisk
}

/// <summary>Identifies Crystal sub-nodes with their type.</summary>
public struct CrystalSubNodeTag : IComponentData
{
    public CrystalSubNodeType Type;
}

// ==================== Crystal Node Systems ====================

/// <summary>
/// Attached to any Crystal node (main or sub) that spreads the curse.
/// </summary>
public struct CrystalNode : IComponentData
{
    public byte IsMain;             // 1 = main hive/bud, 0 = sub-node
    public float SpreadPerTick;     // Cells per tick (logical units)
    public float SpreadRadius;      // World radius
    public float IncomePerTick;     // Resource trickle for crystals
    public float TickInterval;      // Seconds between ticks
    public float TickTimer;         // Accumulated time
    public byte Enabled;
}

/// <summary>
/// Tracks the Crystal faction global level and XP.
/// </summary>
public struct CrystalLevelState : IComponentData
{
    public int Level;           // 1..5
    public int Xp;              // Current XP
    public int XpToNext;        // XP needed for next level
    public float HarassTimer;   // Timer until next harassment wave
}

/// <summary>
/// Noise generated by player mining near cursed ground.
/// Attracts Crystal attention.
/// </summary>
public struct CrystalMiningNoise : IComponentData
{
    public int LocalNoise; // Noise value for the region
}

// ==================== Crystal Abilities ====================

/// <summary>
/// Rally ability cooldown per Main Node.
/// </summary>
public struct CrystalRally : IComponentData
{
    public float Cooldown;  // Total cooldown in seconds
    public float Timer;     // Accumulated time
}

/// <summary>
/// Aura effects emanating from Main Nodes at Level 2+.
/// </summary>
public struct CrystalMainAuras : IComponentData
{
    public float AllyAspdPct;       // Attack speed bonus to Crystal allies
    public float AllyMovePct;       // Movement speed bonus to Crystal allies
    public float EnemyArmorPct;     // Armor reduction to enemies
    public float EnemyAccuracyPct;  // Accuracy reduction to enemies
    public float Radius;            // Aura effect radius
    public byte Enabled;
}

/// <summary>
/// Teleport link marker for Nexus nodes.
/// </summary>
public struct CrystalNexus : IComponentData
{
    public Entity Linked;   // Another Nexus (bidirectional link)
    public byte Streams;    // Concurrent teleport streams allowed
}

/// <summary>
/// Siege lattice linking (Level 4 feature).
/// Marks when a node is part of a cluster.
/// </summary>
public struct CrystalLatticeMember : IComponentData
{
    public byte InCluster;
    public byte BonusProjectiles; // +1 beams/bolts when clustered
}

/// <summary>
/// Ultimate ability toggles at Level 5.
/// </summary>
public struct CrystalUltimateState : IComponentData
{
    public byte EmbraceActive;       // 1 if Crystal's Embrace is running
    public float EmbraceTimer;
    public byte TamingProtocolReady;
}