// TerrainOverlayMaterialBinder.cs
// Restores the ORIGINAL curse/blood/territory ground renderer (2026-08-03):
// the per-pixel TWB/Terrain/Lit overlay stack (TWBTerrainOverlays.hlsl fed
// by InfluenceMaskTexture's world-space masks — SC2-creep-style noise-eroded
// fronts, no alphamap writes, no ticks, no flicker).
//
// Why this exists: the hand-authored map scenes used to carry the
// TWBTerrain material on their Terrain objects. The scene reorg deleted
// those scenes, and map terrain is now RUNTIME-GENERATED by MapMagic — which
// gives it MapMagic's own material, so the overlay shader never ran and the
// ground fell back to the row-amortized splat painter (visible flicker).
// This binder closes that gap: it assigns the TWBTerrain material
// (Resources/TWBTerrain.mat — curse rock + purple tint, blood, slate,
// terraces, all wired) as every active terrain's materialTemplate, and
// keeps re-asserting it in case MapMagic regenerates or swaps materials.
//
// The shader is a faithful copy of URP Terrain/Lit, so the terrain's own
// authored splats render identically — only the overlays are added.

using UnityEngine;
using UnityEngine.SceneManagement;
using TheWaningBorder.Core.Maps;

namespace TheWaningBorder.Influence
{
    [DefaultExecutionOrder(1999)] // just before InfluenceMaskTexture (2000)
    public sealed class TerrainOverlayMaterialBinder : MonoBehaviour
    {
        private const float CheckInterval = 1f;

        private Material _material;
        private float _nextCheck;

        // ─── Auto-mount on gameplay scenes ────────────────────────────────
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
        private static void Init()
        {
            SceneManager.sceneLoaded -= OnSceneLoaded;
            SceneManager.sceneLoaded += OnSceneLoaded;
            OnSceneLoaded(SceneManager.GetActiveScene(), LoadSceneMode.Single);
        }

        private static void OnSceneLoaded(Scene scene, LoadSceneMode mode)
        {
            if (!MapRegistry.IsGameplayScene(scene.name)) return;
            if (Object.FindFirstObjectByType<TerrainOverlayMaterialBinder>() != null) return;
            new GameObject("[Terrain Overlay Material Binder]")
                .AddComponent<TerrainOverlayMaterialBinder>();
        }

        private void Awake()
        {
            _material = Resources.Load<Material>("TWBTerrain");
            if (_material == null)
                Debug.LogWarning("[TerrainOverlayMaterialBinder] Resources/TWBTerrain.mat missing — " +
                                 "ground overlays (curse/blood/territory) will not render.");
        }

        private void Update()
        {
            if (_material == null) return;
            if (Time.time < _nextCheck) return;
            _nextCheck = Time.time + CheckInterval;

            // MapMagic can spawn terrain late and re-apply its own material on
            // regeneration — re-assert ours whenever it differs. Covers multi-
            // tile maps too.
            var terrains = Terrain.activeTerrains;
            for (int i = 0; i < terrains.Length; i++)
            {
                var t = terrains[i];
                if (t == null || t.materialTemplate == _material) continue;
                t.materialTemplate = _material;
                TWBLog.Log($"[TerrainOverlayMaterialBinder] bound TWB/Terrain/Lit to '{t.name}'.");
            }
        }
    }
}
